<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EVB7C84" failures="0" tests="11" name="TestNGClass.ExceptionExpected" time="0.073" errors="0" timestamp="2023-09-08T19:57:17 IST" skipped="0">
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.005"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="loginText" time="0.002"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.003"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.005"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.007"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.006"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.005"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.015"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.012"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.009"/>
  <testcase classname="TestNGClass.ExceptionExpected" name="logText" time="0.004"/>
</testsuite> <!-- TestNGClass.ExceptionExpected -->
